site_name: Pharmacy RFM Lens
site_url: https://TAbramovskaya.github.io/sml-metabase-final-project/
theme:
  name: material
  palette:
    primary: black
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  nav_style: expand
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list     # ← добавляешь сюда
  - pymdownx.details
nav:
  - Summary: index.md
  - Source: db_overview.md
  - Data preprocessing: data_preprocessing.md
  - Handling NULLs: null_barcodes_overview.md
  - Unusual behaviour: unusual_behavior_overview.md
  - Inconsistent data: inconsistent_data_overview.md
  - RFM aggregated data: rfm_aggregated_data.md
  - RFM calculation methodology: rfm_calculation_methodology.md
  - Recency: recency_study.md
  - Frequency: frequency_study.md
  - Monetary: monetary_study.md
  - Behavior & Segmentation: rfm_behavior.md
  - Insights & Recommendations: rfm_finalize.md

extra_css:
  - styles.css  # optional for custom styling
extra_javascript:
  - scripts.js # optional for custom JS